-- MySQL Script generated by MySQL Workbench
-- Thu 19 Nov 2015 08:05:23 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_equations
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_equations
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_equations` DEFAULT CHARACTER SET utf8 ;
USE `db_equations` ;

-- -----------------------------------------------------
-- Table `db_equations`.`equations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_equations`.`equations` (
  `equation` VARCHAR(45) NOT NULL,
  `answer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`equation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_equations`.`likely_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_equations`.`likely_answers` (
  `equation` VARCHAR(45) NOT NULL,
  `likely_answer` VARCHAR(45) NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  `count` INT NOT NULL,
  INDEX `producto_notable_idx` (`equation` ASC),
  CONSTRAINT `fk_eq`
    FOREIGN KEY (`equation`)
    REFERENCES `db_equations`.`equations` (`equation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_equations`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_equations`.`student` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_equations`.`given_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_equations`.`given_answers` (
  `id_answer` INT NOT NULL AUTO_INCREMENT,
  `equation` VARCHAR(45) NOT NULL,
  `user` INT NOT NULL,
  `answer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_answer`),
  INDEX `producto_notable_idx` (`equation` ASC),
  INDEX `usuario_idx` (`user` ASC),
  CONSTRAINT `fk_equation`
    FOREIGN KEY (`equation`)
    REFERENCES `db_equations`.`equations` (`equation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user`)
    REFERENCES `db_equations`.`student` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
